### PR TITLE
fix(Uplaod): support upload again when an upload fails, close #4849

### LINKED ISSUE #4849: [Upload]Upload组件手动上传第一次接口报错后，再点击上传，没有调用接口
### Component 
Upload

### Reproduction link 
[https://fusion.alibaba-inc.com/dsm/pc/components/detail/upload?themeid=40463&tabActiveKey=component#submit-container](https://fusion.alibaba-inc.com/dsm/pc/components/detail/upload?themeid=40463&tabActiveKey=component#submit-container)

### Steps to reproduce
可以通过官网的“不自动上传”示例复现，第一次上传时，接口报错，再点击上传，没有调接口，除非删除当前文件重新选择一个才能上传，期望每次执行startUpload都能调用接口，否则服务不稳定时候，无法继续使用当前文件进行重试

### PR DESCRIPTION
**Pull request by FairyYang**
close #4849

### CODE REVIEW

File: components/upload/upload.tsx [hunk 1]
```diff
@@ -188,7 +188,11 @@ class Upload extends Base<UploadProps, UploadState> {
         this.state.uploading = true;
         const fileList = files
             .filter(file => {
-                if (file.state === 'selected') {
+                if (
+                    file.state === 'selected' ||
+                    file.state === 'error' ||
+                    file.state === 'uploading'
```
Comment (eternalsky) [inline components/upload/upload.tsx:194]: 为什么这里还会带进去一个 file.state 等于 uploading 的情况

**Review by eternalsky — CHANGES_REQUESTED** [review]

**Review by eternalsky — APPROVED** [review]
