### PR TITLE
fix(Range): repair browser count float issue, close #3652

### LINKED ISSUE #3652: [Range]Range展示问题
### Component 
Range

### Steps to reproduce
Range 最大值为1，最小值为0.1 step为0.1 在拖拽到0.3和0.8时展示不正确

### PR DESCRIPTION
**Pull request by weinianyang**

### CODE REVIEW

**Comment by bindoon** [comment]
格式化太多，改了哪里标记下

**Comment by weinianyang** [comment]
> 其他，改了下标签

https://github.com/alibaba-fusion/next/pull/3761/files#diff-5cefacbb9e48c036085483821212d15adb42481c4d18901924f6accdff5188d8R557

File: src/range/view/range.jsx [hunk 1]
```diff
@@ -619,12 +552,11 @@ class Range extends React.Component {
...
         const newValue = parseFloat(
-            (Math.round(((percent / 100) * (max - min)) / step) * step).toFixed(
-                getPrecision(step)
-            )
+            (Math.round(((percent / 100) * (max - min)) / step) * step).toFixed(getPrecision(step))
         );
+        const currentValue = (min + newValue).toFixed(getPrecision(step));
 
-        return min + newValue;
+        return Number(currentValue);
```
Comment (bindoon) [inline src/range/view/range.jsx:559]: toFixed 之后一定是数字吧，感觉不需要 Number

**Review by bindoon — APPROVED** [review]
