### PR TITLE
fix(TreeSelect): bug after setState onSearch, close #2029

### LINKED ISSUE #2029: [TreeSelect]treeSelect获取搜索动态数据源不填充
### Component 
TreeSelect
### Feature Description
在输入框中输入关键字，获取得到新数据，此时新数据无法变更数据源

### PR DESCRIPTION
**Pull request by jerryyxu**

### CODE REVIEW

File: src/tree-select/tree-select.jsx [hunk 1]
```diff
@@ -475,33 +505,36 @@ class TreeSelect extends Component {
...
-                        const p = posArr.slice(0, i + 1).join('-');
-                        const kk = this.state._p2n[p].key;
-                        if (retainedKeys.indexOf(kk) === -1) {
-                            retainedKeys.push(kk);
-                        }
-                    }
-                });
-            }
-        });
+        // const searchedKeys = [];
```
Comment (youluna) [inline src/tree-select/tree-select.jsx:508]: 删掉注释

**Review by youluna — COMMENTED** [review]
可以加一个docs下的demo，参考 https://codesandbox.io/s/elated-hermann-h2tic?file=/index.js

**Review by youluna — APPROVED** [review]
