### PR TITLE
fix(Select): optimize controlled highlightKey question, close #3795

### LINKED ISSUE #3795: [Select]Select 在指定 value 的情况下高亮和选中表现不一致
### Component 
Select

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/e9f3a82a](https://riddle.alibaba-inc.com/riddles/e9f3a82a)

### Steps to reproduce
Select 在指定 value 的情况下高亮和选中表现不一致。

### PR DESCRIPTION
**Pull request by weinianyang**

### CODE REVIEW

File: src/select/select.jsx [hunk 1]
```diff
@@ -260,6 +260,13 @@ class Select extends Base {
...
 
+        // 受控value应赋值给 highlightKey
+        if ('value' in nextProps) {
+            Object.assign(state, {
+                highlightKey: nextProps.value,
+            });
+        }
+
         if ('value' in nextProps && nextProps.value !== prevState.value) {
             Object.assign(state, {
```
Comment (bindoon) [inline src/select/select.jsx:271]: 挪到这里来，并且限制下 single 单选模式才赋值

**Review by bindoon — APPROVED** [review]
