### PR TITLE
fix(Upload): value must be Array close #2019

### LINKED ISSUE #2019: [Upload]Uploader.Card break down when value is not array
### Component 
Upload

### Steps to reproduce
Version: @alifd/next 1.20.18

### PR DESCRIPTION
**Pull request by bindoon**

### CODE REVIEW

File: src/upload/card.jsx [hunk 1]
```diff
@@ -59,7 +59,7 @@ class Card extends Base {
         }
 
         this.state = {
-            value: typeof value === 'undefined' ? [] : value,
+            value: typeof value === 'undefined' || !Array.isArray(value) ? [] : value,
```
Comment (youluna) [inline src/upload/card.jsx:62]: `!Array.isArray(value)`是不是就够了 不需要再 `typeof value === 'undefined'`
