### PR TITLE
fix(DatePicker): resolve bugs when to use hooks, close #1640

### LINKED ISSUE #1640: [DatePicker]DatePicker在同时监听onBlur/onFocus的时候切换月份失败
### Component 
DatePicker

### Reproduction link 
[Edit on CodeSandbox](https://codesandbox.io/s/young-flower-s11m5)

### PR DESCRIPTION
**Pull request by acejerry**

### CODE REVIEW

**Comment by youluna** [comment]
加个单测吧

File: src/calendar/calendar.jsx [hunk 1]
```diff
@@ -160,6 +159,20 @@ class Calendar extends Component {
...
+        if (value && oldVlaue) {
+            if (!moment.isMoment(value)) {
+                value = moment(value);
+            }
+            if (!moment.isMoment(oldVlaue)) {
+                oldVlaue = moment(oldVlaue);
+            }
+            return value.valueOf() !== oldVlaue.valueOf();
+        } else {
+            return value === oldVlaue;
```
Comment (youluna) [inline src/calendar/calendar.jsx:172]: 是不是应该是 value !== oldValue
