### PR TITLE
fix(Table): should support for should support for merging cells

### LINKED ISSUE #4264: [Table]table 合并单元格有问题
### Component 
Table

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/39861561](https://riddle.alibaba-inc.com/riddles/39861561)

### Steps to reproduce
锁列时合并单元格有问题，可以直接看链接上的效果

image

### PR DESCRIPTION
**Pull request by kyokaxin**
in locked columns, close #4264

### CODE REVIEW

File: components/table/new-lock.jsx [hunk 1]
```diff
@@ -307,7 +307,25 @@ export default function stickyLock(BaseComponent) {
...
+                            return parseFloat(getComputedStyle(tmpNode).width) / tmpNode.colSpan || 0;
+                        } else {
+                            return 0;
+                        }
+                    }
+                };
+                if (node) {
+                    colWidth = parseFloat(getComputedStyle(node).width) / node.colSpan || 0;
+                } else {
+                    colWidth = checkMatchingMergeColSpan(nodeToGetWidth);
```
Comment (YSMJ1994) [inline components/table/new-lock.jsx:327]: 用户的问题好像上面那个if就解决了，这个else里面是在什么情况下会使用呢

**Review by YSMJ1994 — APPROVED** [review]
