### PR TITLE
fix(Overlay): support show-hide in nested scroll component

### LINKED ISSUE #4481: [Overlay]Select 组件在「表格组件锁列的情况」下使用时，popupProps 使用 v2   autoAdjust 时，判断 trigger 不可见时弹层没有消失， z-index 层级也不太对
### Component 
Overlay

### Reproduction link 
[Edit on CodeSandbox](https://codesandbox.io/s/condescending-gates-x8jmmf?file=/src/App.js)

### Steps to reproduce
期望 Trigger 元素不可见时，弹层隐藏

### PR DESCRIPTION
**Pull request by kyokaxin**
close #4481

### CODE REVIEW

File: test/overlay/index-spec.js [hunk 1]
```diff
@@ -1079,4 +1079,54 @@ describe('Popup', () => {
 
         assert(buttonDom);
     });
+
+    it('fix support show-hide in nested scroll component', async function() {
+        this.timeout(30000);
```
Comment (YSMJ1994) [inline test/overlay/index-spec.js:1084]: 这个去掉吧

**Review by YSMJ1994 — APPROVED** [review]
