### PR TITLE
fix(DatePicker2): value controlled issue, close #2641

### LINKED ISSUE #2641: [DatePicker2]DatePicker2 不支持Form 组件的 name属性，并且报错
### Component 
DatePicker2

### Steps to reproduce
DatePicker2 不支持 Form组件的name 属性，并且 报错：

image

### PR DESCRIPTION
**Pull request by jerryyxu**

### CODE REVIEW

File: src/date-picker2/prop-types.js [hunk 1]
```diff
@@ -31,7 +31,7 @@ const SharedPT = {
         }
     },
     value(props, propName, componentName) {
-        if (propName in props) {
+        if (props[propName] !== undefined) {
             let value = props[propName];
```
Comment (jerryyxu) [inline src/date-picker2/prop-types.js:35]: RangePicker 传undefined 会warn

**Review by youluna — APPROVED** [review]
