### PR TITLE
fix(CascaderSelect): resolve resultAutoWidth prop unuseless, close #1710

### LINKED ISSUE #1710: [CascaderSelect]CascaderSelect在开启showSearch后，设置resultAutoWidth=false不生效
### Component 
CascaderSelect

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/2ab838fd](https://riddle.alibaba-inc.com/riddles/2ab838fd)

### Steps to reproduce
开启showSearch，resultAutoWidth设为false后，搜索结果列表的宽度依然和选择框等宽，配置并未生效

### PR DESCRIPTION
**Pull request by acejerry**

### CODE REVIEW

File: test/cascader-select/index-spec.js [hunk 1]
```diff
@@ -491,6 +497,38 @@ describe('CascaderSelect', () => {
...
+            />, container);
+        })
+
+        const iptElem = document.querySelector('.cs-auto-width input');
+
+        ReactTestUtils.Simulate.input(iptElem);
+        iptElem.value = '杭州';
+        ReactTestUtils.Simulate.change(iptElem);
+        setTimeout(() => {
+            assert(document.querySelector('.result-auto-width-popup').style.width === '');
```
Comment (youluna) [inline test/cascader-select/index-spec.js]: 要加一下销毁的逻辑
