### PR TITLE
fix(Drawer): rollback body style while unmount fix #3725

### LINKED ISSUE #3725: [Dialog]v2 unmout 卸载的时候没恢复环境
### Component 
Dialog

### Reproduction link 
直接卸载的时候没有恢复 body 滚动环境
[https://riddle.alibaba-inc.com/riddles/490a481a](https://riddle.alibaba-inc.com/riddles/490a481a)

### PR DESCRIPTION
**Pull request by bindoon**

### CODE REVIEW

File: src/drawer/drawer-v2.jsx [hunk 1]
```diff
@@ -172,11 +180,35 @@ const Drawer = props => {
         }
     }, [container]);
 
+    const handleExited = () => {
```
Comment (lakerswgq) [inline src/drawer/drawer-v2.jsx:183]: 最好有些注释方便理解

**Review by lakerswgq — APPROVED** [review]
